apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-application.fullname" . }}
  labels:
    {{- include "notifications-application.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: notificationsApplication
      cloud:
        discovery:
          enabled: false        
        config:
          enabled: false      
      datasource:
        url: {{ tpl .Values.config.database_url . | quote }}
        username: {{ .Values.config.database_username | quote }}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
      liquibase:
        enabled: true
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ tpl .Values.keycloak.issuer_uri . | quote }}
      kafka:
        bootstrap-servers: {{ tpl .Values.kafka.url . | quote }}
        consumer:
          group-id: notify-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: ru.yandex.practicum.yaBank.notificationsApplication.dto
        listener:
          observation-enabled: true
          ack-mode: RECORD
        admin:
          client-id: yandex-practicum
        properties:
          security.protocol: PLAINTEXT
    server:
      port: {{ .Values.service.port }}
    eureka:
      client:
        enabled: false
    logging:
      level:
        liquibase: DEBUG    
